// <auto-generated />
namespace GigHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Notifications_ROProps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Notifications_ROProps));
        
        string IMigrationMetadata.Id
        {
            get { return "202005031508424_Notifications_ROProps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
